version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./:/app
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: